/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { PlaylistUpdateManyWithoutUsersInput } from "./PlaylistUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { SingerUpdateManyWithoutUsersInput } from "./SingerUpdateManyWithoutUsersInput";
import { SubscriptionUpdateManyWithoutUsersInput } from "./SubscriptionUpdateManyWithoutUsersInput";
import { TrackUpdateManyWithoutUsersInput } from "./TrackUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: () => PlaylistUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PlaylistUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PlaylistUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  playlists?: PlaylistUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => SingerUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SingerUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SingerUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  singers?: SingerUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => SubscriptionUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => SubscriptionUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => SubscriptionUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  subscriptions?: SubscriptionUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TrackUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TrackUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TrackUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  tracks?: TrackUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
